// editor/src/components/editor/timeline/index.tsx
'use client';

import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Video,
  Music,
  TypeIcon,
  SparklesIcon,
  Image,
  Ellipsis,
  ArrowUp,
  ArrowDown,
} from 'lucide-react';
import { useTimelineStore } from '@/stores/timeline-store';
import { usePlaybackStore } from '@/stores/playback-store';
import { useStudioStore } from '@/stores/studio-store';

import { useTimelineZoom } from '@/hooks/use-timeline-zoom';

import { useState, useRef, useEffect, useCallback } from 'react';
import { cn } from '@/lib/utils';
import {
  TimelinePlayhead,
  useTimelinePlayheadRuler,
} from './timeline-playhead';
import type { TimelineTrack } from '@/types/timeline';
import { TimelineRuler } from './timeline-ruler';
import {
  getTrackHeight,
  TIMELINE_CONSTANTS,
  snapTimeToFrame,
} from '@/components/editor/timeline/timeline-constants';
import { TimelineToolbar } from './timeline-toolbar';
import { TimelineCanvas } from './timeline';
import { TimelineStudioSync } from './timeline-studio-sync';
import { useEditorHotkeys } from '@/hooks/use-editor-hotkeys';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Button } from '@/components/ui/button';

export function Timeline() {
  const { tracks, clips, getTotalDuration } = useTimelineStore();
  const { duration, seek, setDuration } = usePlaybackStore();
  const { studio } = useStudioStore();

  const timelineRef = useRef<HTMLDivElement>(null);
  const rulerRef = useRef<HTMLDivElement>(null);
  const [isInTimeline, setIsInTimeline] = useState(false);

  // Track mouse down/up for distinguishing clicks from drag/resize ends
  const mouseTrackingRef = useRef({
    isMouseDown: false,
    downX: 0,
    downY: 0,
    downTime: 0,
  });

  // Timeline zoom functionality
  const { zoomLevel, setZoomLevel, handleWheel } = useTimelineZoom({
    containerRef: timelineRef,
    isInTimeline,
  });

  // Old marquee selection removed - using new SelectionBox component instead

  // Dynamic timeline width calculation based on playhead position and duration
  const dynamicTimelineWidth = Math.max(
    (duration || 0) * TIMELINE_CONSTANTS.PIXELS_PER_SECOND * zoomLevel, // Base width from duration
    timelineRef.current?.clientWidth || 1000 // Minimum width
  );

  // Scroll synchronization and auto-scroll to playhead
  const rulerScrollRef = useRef<HTMLDivElement>(null);
  const tracksScrollRef = useRef<HTMLDivElement>(null);
  const trackLabelsRef = useRef<HTMLDivElement>(null);
  const playheadRef = useRef<HTMLDivElement>(null);
  const timelineCanvasRef = useRef<TimelineCanvas | null>(null);
  const isUpdatingRef = useRef(false);

  // Timeline playhead ruler handlers
  const { handleRulerMouseDown } = useTimelinePlayheadRuler({
    duration,
    zoomLevel,
    seek,
    rulerRef,
    rulerScrollRef,
    tracksScrollRef,
    playheadRef,
  });

  // Timeline content click to seek handler
  const handleTimelineContentClick = useCallback(
    (e: React.MouseEvent) => {
      const { isMouseDown, downX, downY, downTime } = mouseTrackingRef.current;

      // Reset mouse tracking
      mouseTrackingRef.current = {
        isMouseDown: false,
        downX: 0,
        downY: 0,
        downTime: 0,
      };

      // Only process as click if we tracked a mouse down on timeline background
      if (!isMouseDown) {
        return;
      }

      // Check if mouse moved significantly (indicates drag, not click)
      const deltaX = Math.abs(e.clientX - downX);
      const deltaY = Math.abs(e.clientY - downY);
      const deltaTime = e.timeStamp - downTime;

      if (deltaX > 5 || deltaY > 5 || deltaTime > 500) {
        return;
      }

      // Don't seek if clicking on timeline elements, but still deselect
      if ((e.target as HTMLElement).closest('.timeline-element')) {
        return;
      }

      // Don't seek if clicking on playhead
      if (playheadRef.current?.contains(e.target as Node)) {
        return;
      }

      // Clear selected elements when clicking empty timeline area

      // Determine if we're clicking in ruler or tracks area
      const isRulerClick = (e.target as HTMLElement).closest(
        '[data-ruler-area]'
      );

      let mouseX: number;
      let scrollLeft = 0;

      if (isRulerClick) {
        // Calculate based on ruler position
        const rulerContent = rulerScrollRef.current;
        if (!rulerContent) {
          return;
        }
        const rect = rulerContent.getBoundingClientRect();
        mouseX = e.clientX - rect.left;
        scrollLeft = rulerContent.scrollLeft;
      } else {
        const tracksContent = tracksScrollRef.current;
        if (!tracksContent) {
          // If tracksScrollRef is gone (because we removed it), we can try to use canvas container if possible,
          // or just rely on ruler if we assume vertical stack is aligned.
          // But playhead seeking usually depends on ruler X.
          // If the user clicked elsewhere?
          // In the new layout, timeline-canvas is in a div. We didn't ref it for clicking yet.
          // But handleTimelineContentClick is attached to...
          // Wait, I removed the "tracksContainerRef" attachment in the previous step?
          // "onMouseDown={handleTimelineMouseDown} ... ref={tracksContainerRef}" was on the removed div.
          // So click seeking on the canvas tracks area MIGHT BE BROKEN unless I re-attach listeners.
          return;
        }
        const rect = tracksContent.getBoundingClientRect();
        mouseX = e.clientX - rect.left;
        scrollLeft = tracksContent.scrollLeft;
      }

      const rawTime = Math.max(
        0,
        Math.min(
          duration,
          (mouseX + scrollLeft) /
            (TIMELINE_CONSTANTS.PIXELS_PER_SECOND * zoomLevel)
        )
      );

      // Use frame snapping for timeline clicking
      const projectFps = 30;
      const time = snapTimeToFrame(rawTime, projectFps);
      seek(time);
    },
    [duration, zoomLevel, seek, rulerScrollRef, tracksScrollRef]
  );

  // Update timeline duration when tracks change
  useEffect(() => {
    const totalDuration = getTotalDuration();
    setDuration(totalDuration);
  }, [tracks, clips, setDuration, getTotalDuration]);

  // --- Scroll synchronization effect ---
  // Horizontal scroll synchronization (Ruler -> Canvas) is now handled via canvas.initScrollbars
  // but we still need to keep the UI in sync when the canvas scrolls.

  useEffect(() => {
    const canvas = new TimelineCanvas('timeline-canvas');
    timelineCanvasRef.current = canvas;

    // Set up UI event listeners (scroll/zoom)
    canvas.on('scroll', ({ deltaX, deltaY, scrollX, scrollY }) => {
      if (isUpdatingRef.current) return;
      isUpdatingRef.current = true;

      if (typeof scrollX === 'number' && rulerScrollRef.current) {
        rulerScrollRef.current.scrollLeft = scrollX;
      } else if (deltaX !== 0 && rulerScrollRef.current) {
        rulerScrollRef.current.scrollLeft += deltaX;
      }

      if (typeof scrollY === 'number' && trackLabelsRef.current) {
        trackLabelsRef.current.scrollTop = scrollY;
      } else if (deltaY !== 0 && trackLabelsRef.current) {
        trackLabelsRef.current.scrollTop += deltaY;
      }

      isUpdatingRef.current = false;
    });

    canvas.on('zoom', ({ delta, zoomLevel: newZoomLevel }) => {
      if (typeof newZoomLevel === 'number') {
        setZoomLevel(newZoomLevel);
        return;
      }
      handleWheel({
        ctrlKey: true,
        deltaY: delta,
        preventDefault: () => {},
        stopPropagation: () => {},
      } as any);
    });

    canvas.initScrollbars({
      offsetX: 0,
      offsetY: 0,
      extraMarginX: 50,
      extraMarginY: 15,
      scrollbarWidth: 8,
      scrollbarColor: 'rgba(255, 255, 255, 0.3)',
    });

    canvas.setTracks(tracks);

    return () => {
      canvas.dispose();
    };
  }, []);

  // Listen for clip replacement (e.g. Placeholder -> Video)
  useEffect(() => {
    const studio = useStudioStore.getState().studio;
    if (!studio) return;

    const onReplaced = ({ newClip }: { newClip: any }) => {
      // Reload the clip in the timeline canvas to fetch thumbnails
      // We use newClip.id as it's the active clip now
      timelineCanvasRef.current?.reloadClip(newClip.id);
    };

    studio.on('clip:replaced', onReplaced);

    return () => {
      studio.off('clip:replaced', onReplaced);
    };
  }, []);

  useEffect(() => {
    if (timelineCanvasRef.current) {
      timelineCanvasRef.current.setTimeScale(zoomLevel);
      timelineCanvasRef.current.setTracks(tracks);
    }
  }, [zoomLevel, tracks, clips]);

  const handleDelete = useCallback(() => {
    studio?.deleteSelected();
  }, [studio]);

  const handleDuplicate = useCallback(() => {
    studio?.duplicateSelected();
  }, [studio]);

  const handleSplit = useCallback(() => {
    // Current time is in seconds in PlaybackStore. Canvas expects microseconds.
    const splitTime = usePlaybackStore.getState().currentTime * 1_000_000;
    studio?.splitSelected(splitTime);
  }, [studio]);

  useEditorHotkeys({
    timelineCanvas: timelineCanvasRef.current,
    setZoomLevel,
  });

  return (
    <div
      className={
        'h-full flex flex-col transition-colors duration-200 relative bg-panel rounded-sm overflow-hidden'
      }
      onMouseEnter={() => setIsInTimeline(true)}
      onMouseLeave={() => setIsInTimeline(false)}
    >
      <TimelineToolbar
        zoomLevel={zoomLevel}
        setZoomLevel={setZoomLevel}
        onDelete={handleDelete}
        onDuplicate={handleDuplicate}
        onSplit={handleSplit}
      />
      <TimelineStudioSync timelineCanvas={timelineCanvasRef.current} />

      {/* Timeline Container */}
      <div
        className="flex-1 flex flex-col overflow-hidden relative bg-[#161412]"
        ref={timelineRef}
      >
        <TimelinePlayhead
          duration={duration}
          zoomLevel={zoomLevel}
          tracks={tracks}
          seek={seek}
          rulerRef={rulerRef}
          rulerScrollRef={rulerScrollRef}
          tracksScrollRef={tracksScrollRef}
          trackLabelsRef={trackLabelsRef}
          timelineRef={timelineRef}
          playheadRef={playheadRef}
          isSnappingToPlayhead={false}
        />

        {/* Timeline Header with Ruler */}
        <div
          style={{ opacity: duration === 0 ? 0 : 1 }}
          className="flex sticky top-0"
        >
          {/* Track Labels Header */}
          <div className="w-16 shrink-0 bg-panel border-r flex items-center justify-between h-6">
            {/* Empty space */}
            <span className="text-sm font-medium text-muted-foreground opacity-0">
              .
            </span>
          </div>

          {/* Timeline Ruler */}
          <div
            className="flex-1 relative overflow-hidden h-6"
            onWheel={(e) => {
              // Check if this is horizontal scrolling - if so, don't handle it here
              if (e.shiftKey || Math.abs(e.deltaX) > Math.abs(e.deltaY)) {
                return; // Let ScrollArea handle horizontal scrolling
              }
              handleWheel(e);
            }}
            onClick={handleTimelineContentClick}
            data-ruler-area
          >
            <ScrollArea
              className="w-full scrollbar-hidden"
              ref={rulerScrollRef}
              onScroll={(e) => {
                if (isUpdatingRef.current) return;
                isUpdatingRef.current = true;
                const scrollX = (e.currentTarget as HTMLDivElement).scrollLeft;
                timelineCanvasRef.current?.setScroll(scrollX, undefined);
                isUpdatingRef.current = false;
              }}
            >
              <div
                ref={rulerRef}
                className="relative h-6 select-none cursor-default"
                style={{
                  width: `${dynamicTimelineWidth}px`,
                }}
                onMouseDown={handleRulerMouseDown}
              >
                <TimelineRuler
                  zoomLevel={zoomLevel}
                  duration={duration}
                  width={dynamicTimelineWidth}
                />
              </div>
            </ScrollArea>
          </div>
        </div>

        {/* Tracks Area */}
        <div className="flex-1 flex overflow-hidden">
          {/* Track Labels */}
          {tracks.length > 0 && (
            <div
              ref={trackLabelsRef}
              className="w-16 shrink-0 overflow-y-hidden z-100"
              data-track-labels
            >
              <div className="flex flex-col">
                {tracks.map((track, index) => (
                  <div key={track.id}>
                    {/* Top separator for first track */}
                    {index === 0 && (
                      <div
                        className="w-full"
                        style={{
                          height: `${TIMELINE_CONSTANTS.TRACK_PADDING_TOP}px`,
                          marginBottom: '0px',
                          background: 'transparent',
                        }}
                      />
                    )}

                    <div
                      className={cn(
                        'flex items-center px-3 group bg-stone-800'
                      )}
                      style={{ height: getTrackHeight(track.type as any) }}
                    >
                      <div className="flex items-center justify-center flex-1 min-w-0 gap-1">
                        <TrackIcon track={track} />
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="size-4 p-0 hover:bg-stone-700 h-6 w-4"
                            >
                              <Ellipsis className="size-3 text-muted-foreground" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="start" side="right">
                            <DropdownMenuItem
                              disabled={index === 0}
                              onClick={() => {
                                const { moveTrack } =
                                  useTimelineStore.getState();
                                moveTrack(track.id, index - 1);
                              }}
                            >
                              <ArrowUp className="size-4 mr-2" />
                              Move track up
                            </DropdownMenuItem>
                            <DropdownMenuItem
                              disabled={index === tracks.length - 1}
                              onClick={() => {
                                const { moveTrack } =
                                  useTimelineStore.getState();
                                moveTrack(track.id, index + 1);
                              }}
                            >
                              <ArrowDown className="size-4 mr-2" />
                              Move track down
                            </DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                    </div>

                    {/* Separator after each track */}
                    <div
                      className="w-full relative"
                      style={{
                        height: `${TIMELINE_CONSTANTS.TRACK_SPACING}px`,
                        background: 'transparent',
                      }}
                    ></div>
                  </div>
                ))}
                {/* Spacer to match canvas extraMarginY */}
                <div style={{ height: '15px', flexShrink: 0 }} />
              </div>
            </div>
          )}

          {/* Timeline Tracks Content */}
          <div className="flex-1 relative overflow-hidden">
            <div id="timeline-canvas" className="w-full h-full" />
          </div>
        </div>
      </div>
    </div>
  );
}

function TrackIcon({ track }: { track: TimelineTrack }) {
  return (
    <>
      {track.type === 'Image' && (
        <Image className="w-4 h-4 shrink-0 text-muted-foreground" />
      )}
      {(track.type === 'Video' || track.type === 'Placeholder') && (
        <Video className="w-4 h-4 shrink-0 text-muted-foreground" />
      )}
      {track.type === 'Text' && (
        <TypeIcon className="w-4 h-4 shrink-0 text-muted-foreground" />
      )}
      {track.type === 'Caption' && (
        <TypeIcon className="w-4 h-4 shrink-0 text-muted-foreground" />
      )}
      {track.type === 'Audio' && (
        <Music className="w-4 h-4 shrink-0 text-muted-foreground" />
      )}
      {track.type === 'Effect' && (
        <SparklesIcon className="w-4 h-4 shrink-0 text-muted-foreground" />
      )}
    </>
  );
}

// vue-video-editor/app/components/editor/timeline/Timeline.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch, markRaw } from 'vue';
import { useTimelineStore } from '~/composables/useTimelineStore';
import { usePlaybackStore } from '~/composables/usePlaybackStore';
import { useStudioStore } from '~/composables/useStudioStore';

import { 
  Video, 
  Music, 
  Type as TypeIcon, 
  Sparkles as SparklesIcon, 
  Image as ImageIcon,
  Ellipsis,
  ArrowUp,
  ArrowDown
} from 'lucide-vue-next';

import { TimelineCanvas } from './timeline/index';
import TimelinePlayhead from './TimelinePlayhead.vue';
import TimelineRuler from './TimelineRuler.vue';
import TimelineToolbar from './TimelineToolbar.vue';
import TimelineStudioSync from './TimelineStudioSync.vue';
import { TIMELINE_CONSTANTS, getTrackHeight } from './timeline-constants';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu';
import { Button } from '~/components/ui/button';
import { ScrollArea } from '~/components/ui/scroll-area';

const { state: timelineState, getTotalDuration } = useTimelineStore();
const { state: playbackState, seek, setDuration } = usePlaybackStore();
const { state: studioState } = useStudioStore();

const timelineRef = ref<HTMLElement | null>(null);
const rulerRef = ref<HTMLElement | null>(null);
const rulerScrollRef = ref<any>(null);
const rulerScrollViewport = ref<HTMLElement | null>(null); // Actual scrollable element
const tracksScrollRef = ref<HTMLElement | null>(null);
const trackLabelsRef = ref<HTMLElement | null>(null);
const playheadRef = ref<HTMLElement | null>(null);

const isInTimeline = ref(false);
const zoomLevel = ref(1); // Default zoom

const timelineCanvas = ref<TimelineCanvas | null>(null);
const isUpdating = ref(false);

const tracks = computed(() => timelineState.value.tracks);
const duration = computed(() => playbackState.value.duration);
const studio = computed(() => studioState.value.studio);

const dynamicTimelineWidth = computed(() => {
  return Math.max(
    (duration.value || 0) * TIMELINE_CONSTANTS.PIXELS_PER_SECOND * zoomLevel.value,
    timelineRef.value?.clientWidth || 1000
  );
});

onMounted(() => {
  const canvas = new TimelineCanvas('timeline-canvas');
  // Use markRaw to prevent Vue from making this reactive
  // This is necessary because the Timeline class uses private fields (#)
  // which don't work with Vue's Proxy-based reactivity
  timelineCanvas.value = markRaw(canvas);

  // Extract the actual scrollable viewport from the ScrollArea component
  if (rulerScrollRef.value) {
    // The ScrollArea component has a viewport element with data-slot="scroll-area-viewport"
    const viewport = rulerScrollRef.value.$el?.querySelector('[data-slot="scroll-area-viewport"]') ||
                     rulerScrollRef.value.querySelector?.('[data-slot="scroll-area-viewport"]');
    if (viewport) {
      rulerScrollViewport.value = viewport;
    }
  }

  canvas.on('scroll', ({ deltaX, deltaY, scrollX, scrollY }: any) => {
    if (isUpdating.value) return;
    isUpdating.value = true;

    if (typeof scrollX === 'number' && rulerScrollRef.value) {
      rulerScrollRef.value.scrollLeft = scrollX;
    }
    
    if (typeof scrollY === 'number' && trackLabelsRef.value) {
      trackLabelsRef.value.scrollTop = scrollY;
    }

    isUpdating.value = false;
  });

  canvas.initScrollbars({
    offsetX: 0,
    offsetY: 0,
    extraMarginX: 50,
    extraMarginY: 15,
    scrollbarWidth: 8,
    scrollbarColor: 'rgba(255, 255, 255, 0.3)',
  });

  canvas.setTracks(tracks.value);
});

onUnmounted(() => {
  if (timelineCanvas.value) {
    timelineCanvas.value.dispose();
  }
});

watch([zoomLevel, tracks], () => {
  if (timelineCanvas.value) {
    timelineCanvas.value.setTimeScale(zoomLevel.value);
    timelineCanvas.value.setTracks(tracks.value);
  }
});

const handleDelete = () => {
  studio.value?.deleteSelected();
};

const handleDuplicate = () => {
  studio.value?.duplicateSelected();
};

const handleSplit = () => {
  const splitTime = playbackState.value.currentTime * 1_000_000;
  studio.value?.splitSelected(splitTime);
};

const handleWheel = (e: WheelEvent) => {
  if (e.ctrlKey) {
    e.preventDefault();
    const delta = e.deltaY;
    zoomLevel.value = Math.max(0.15, Math.min(3.5, zoomLevel.value - delta * 0.01));
  }
};

const handleTimelineContentClick = (e: MouseEvent) => {
  // Simplified click-to-seek logic from index.tsx
  const target = e.target as HTMLElement;
  if (target.closest('.timeline-element')) return;
  if (playheadRef.value?.contains(target)) return;

  const isRulerClick = target.closest('[data-ruler-area]');
  let mouseX: number;
  let scrollLeft = 0;

  if (isRulerClick && rulerScrollRef.value) {
    const rect = rulerScrollRef.value.getBoundingClientRect();
    mouseX = e.clientX - rect.left;
    scrollLeft = rulerScrollRef.value.scrollLeft;
  } else if (tracksScrollRef.value) {
    const rect = tracksScrollRef.value.getBoundingClientRect();
    mouseX = e.clientX - rect.left;
    scrollLeft = tracksScrollRef.value.scrollLeft;
  } else {
    return;
  }

  const time = (mouseX + scrollLeft) / (TIMELINE_CONSTANTS.PIXELS_PER_SECOND * zoomLevel.value);
  seek(Math.max(0, Math.min(duration.value, time)));
};
</script>

<template>
  <div
    class="h-full flex flex-col transition-colors duration-200 relative bg-card rounded-sm overflow-hidden"
    @mouseenter="isInTimeline = true"
    @mouseleave="isInTimeline = false"
  >
    <TimelineToolbar
      v-model:zoomLevel="zoomLevel"
      @delete="handleDelete"
      @duplicate="handleDuplicate"
      @split="handleSplit"
    />
    
    <TimelineStudioSync :timelineCanvas="timelineCanvas" />

    <!-- Timeline Container -->
    <div
      ref="timelineRef"
      class="flex-1 flex flex-col overflow-hidden relative bg-[#121212]"
      @wheel="handleWheel"
    >
      <TimelinePlayhead
        :duration="duration"
        :zoomLevel="zoomLevel"
        :tracks="tracks"
        :seek="seek"
        :rulerRef="rulerRef"
        :rulerScrollRef="rulerScrollViewport"
        :tracksScrollRef="tracksScrollRef"
        :trackLabelsRef="trackLabelsRef"
        :timelineRef="timelineRef"
        :playheadRef="playheadRef"
      />

      <!-- Timeline Header with Ruler -->
      <div
        :style="{ opacity: duration === 0 ? 0 : 1 }"
        class="flex sticky top-0 z-20"
      >
        <!-- Track Labels Header -->
        <div class="w-16 shrink-0 bg-card border-r flex items-center justify-between h-6">
          <span class="text-sm font-medium text-muted-foreground opacity-0">.</span>
        </div>

        <!-- Timeline Ruler -->
        <div
          class="flex-1 relative overflow-hidden h-6"
          data-ruler-area
          @click="handleTimelineContentClick"
        >
          <ScrollArea
            ref="rulerScrollRef"
            class="w-full h-full scrollbar-hidden"
            @scroll="(e: any) => {
              if (isUpdating) return;
              isUpdating = true;
              const scrollX = e.target.scrollLeft;
              timelineCanvas?.setScroll(scrollX, undefined);
              isUpdating = false;
            }"
          >
            <div
              ref="rulerRef"
              class="relative h-6 select-none cursor-default"
              :style="{ width: `${dynamicTimelineWidth}px` }"
            >
              <TimelineRuler
                :zoomLevel="zoomLevel"
                :duration="duration"
                :width="dynamicTimelineWidth"
              />
            </div>
          </ScrollArea>
        </div>
      </div>

      <!-- Tracks Area -->
      <div class="flex-1 flex overflow-hidden">
        <!-- Track Labels -->
        <div
          v-if="tracks.length > 0"
          ref="trackLabelsRef"
          class="w-16 shrink-0 overflow-y-hidden z-10 bg-card border-r"
          data-track-labels
        >
          <div class="flex flex-col">
            <template v-for="(track, index) in tracks" :key="track.id">
              <!-- Top separator for first track -->
              <div
                v-if="index === 0"
                :style="{ height: `${TIMELINE_CONSTANTS.TRACK_PADDING_TOP}px` }"
              />

              <div
                class="flex items-center px-3 group bg-input/40"
                :style="{ height: `${getTrackHeight(track.type)}px` }"
              >
                <div class="flex items-center justify-center flex-1 min-w-0 gap-1">
                  <!-- Track Icon Logic -->
                  <ImageIcon v-if="track.type === 'Image'" class="w-4 h-4 shrink-0 text-muted-foreground" />
                  <Video v-else-if="track.type === 'Video' || track.type === 'Placeholder'" class="w-4 h-4 shrink-0 text-muted-foreground" />
                  <TypeIcon v-else-if="track.type === 'Text' || track.type === 'Caption'" class="w-4 h-4 shrink-0 text-muted-foreground" />
                  <Music v-else-if="track.type === 'Audio'" class="w-4 h-4 shrink-0 text-muted-foreground" />
                  <SparklesIcon v-else-if="track.type === 'Effect'" class="w-4 h-4 shrink-0 text-muted-foreground" />
                  
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button variant="ghost" size="icon" class="size-4 p-0 h-6 w-4">
                        <Ellipsis class="size-3 text-muted-foreground" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="start" side="right">
                      <DropdownMenuItem
                        :disabled="index === 0"
                        @click="useTimelineStore().moveTrack(track.id, index - 1)"
                      >
                        <ArrowUp class="size-4 mr-2" />
                        Move track up
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        :disabled="index === tracks.length - 1"
                        @click="useTimelineStore().moveTrack(track.id, index + 1)"
                      >
                        <ArrowDown class="size-4 mr-2" />
                        Move track down
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>

              <!-- Separator after each track -->
              <div
                class="w-full relative"
                :style="{ height: `${TIMELINE_CONSTANTS.TRACK_SPACING}px` }"
              />
            </template>
            <!-- Spacer to match canvas extraMarginY -->
            <div style="height: 15px; flex-shrink: 0" />
          </div>
        </div>

        <!-- Timeline Tracks Content -->
        <div class="flex-1 relative overflow-hidden" ref="tracksScrollRef">
          <div id="timeline-canvas" class="w-full h-full" />
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.scrollbar-hidden::-webkit-scrollbar {
  display: none;
}
.scrollbar-hidden {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
</style>
