// vue-video-editor/app/components/editor/Editor.vue
<script setup lang="ts">
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from '@/components/ui/resizable';
import { ref } from 'vue';
import Header from '@/components/editor/Header.vue';
import CanvasPanel from '@/components/editor/CanvasPanel.vue';
import MediaPanel from '@/components/editor/media-panel/MediaPanel.vue';

// State for panel sizes
const toolsPanelSize = ref(15);
const copilotPanelSize = ref(0);
const mainContentSize = ref(75);
const timelineSize = ref(25);
const isCopilotVisible = ref(false); // Default to hidden for now

// Placeholder for store actions
const setToolsPanel = (size: number) => {
  toolsPanelSize.value = size;
};
const setCopilotPanel = (size: number) => {
  copilotPanelSize.value = size;
};
const setMainContent = (size: number) => {
  mainContentSize.value = size;
};
const setTimeline = (size: number) => {
  timelineSize.value = size;
};
</script>

<template>
  <div class="h-screen w-screen flex flex-col bg-background overflow-hidden space-y-1.5">
    <!-- Header -->
    <Header />

    <div class="flex-1 min-h-0 min-w-0 px-2 pb-2">
      <ResizablePanelGroup
        direction="horizontal"
        class="h-full w-full gap-0"
      >
        <!-- Left Column: Media Panel -->
        <ResizablePanel
          :default-size="toolsPanelSize"
          :min-size="15"
          :max-size="40"
          @resize="setToolsPanel"
          class="max-w-7xl relative overflow-visible! bg-card min-w-0 border-r"
        >
          <MediaPanel />
        </ResizablePanel>

        <ResizableHandle class="bg-transparent w-1.5" />

        <!-- Middle Column: Preview + Timeline -->
        <ResizablePanel
          :default-size="isCopilotVisible ? 100 - copilotPanelSize - toolsPanelSize : 100 - toolsPanelSize"
          :min-size="40"
          class="min-w-0 min-h-0"
        >
          <ResizablePanelGroup
            direction="vertical"
            class="h-full w-full gap-0"
          >
            <!-- Canvas Panel -->
            <ResizablePanel
              :default-size="mainContentSize"
              :min-size="30"
              :max-size="85"
              @resize="setMainContent"
              class="min-h-0 border-b"
            >
              <CanvasPanel />
            </ResizablePanel>

            <ResizableHandle class="bg-transparent !h-1.5" />

            <!-- Timeline Panel -->
            <ResizablePanel
              :default-size="timelineSize"
              :min-size="15"
              :max-size="70"
              @resize="setTimeline"
              class="min-h-0"
            >
              <div class="h-full w-full p-4">
                Timeline Panel
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>

        <template v-if="isCopilotVisible">
          <ResizableHandle class="bg-transparent w-1.5" />
          <!-- Right Column: Chat Copilot -->
          <ResizablePanel
            :default-size="copilotPanelSize"
            :min-size="15"
            :max-size="40"
            @resize="setCopilotPanel"
            class="max-w-7xl relative overflow-visible! bg-card min-w-0 border-l"
          >
             <div class="h-full w-full p-4">
               Copilot Panel
             </div>
          </ResizablePanel>
        </template>
      </ResizablePanelGroup>
    </div>
  </div>
</template>

// apps/app/src/components/editor/editor.tsx
"use client";
import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { MediaPanel } from "@/components/editor/media-panel";
import { CanvasPanel } from "@/components/editor/canvas-panel";
import Timeline from "@/components/editor/timeline";
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from "@/components/ui/resizable";
import { usePanelStore } from "@/stores/panel-store";
import Header from "@/components/editor/header";
import { Loading } from "@/components/editor/loading";
import FloatingControl from "@/components/editor/floating-controls/floating-control";
import { Compositor } from "@openvideo/engine-pixi";
import { WebCodecsUnsupportedModal } from "@/components/editor/webcodecs-unsupported-modal";
import { AssetGeneratorModal } from "@/components/editor/media-panel/asset-generator-modal";
import Assistant from "./assistant/assistant";
import { core } from "@/lib/project";
import { IProject } from "@openvideo/core";
import { spacesAPI } from "@/lib/spaces-api";
import { useProjectStore } from "@/stores/project-store";

export default function Editor({
  initialDesign,
}: {
  isDataLoading?: boolean;
  initialDesign?: IProject;
}) {
  const params = useParams();
  const projectId = params?.projectId as string;

  const setProjectId = useProjectStore((state) => state.setProjectId);
  const setSpaceId = useProjectStore((state) => state.setSpaceId);
  const setProjectName = useProjectStore((state) => state.setProjectName);

  const {
    toolsPanel,
    copilotPanel,
    mainContent,
    timeline,
    setToolsPanel,
    setCopilotPanel,
    setMainContent,
    setTimeline,
    isCopilotVisible,
  } = usePanelStore();

  const [isReady, setIsReady] = useState(false);
  const [isWebCodecsSupported, setIsWebCodecsSupported] = useState(true);

  useEffect(() => {
    if (initialDesign) {
      core.project.import(initialDesign);
    }
  }, [initialDesign]);

  useEffect(() => {
    if (!projectId) return;

    setProjectId(projectId);

    const loadProject = async () => {
      try {
        const projectData = await spacesAPI.get(projectId);
        if (projectData) {
          setSpaceId(projectData.id);
          if (projectData.name) {
            setProjectName(projectData.name);
          }
        }
      } catch (error) {
        console.error("Error loading project in editor:", error);
      }
    };

    loadProject();
  }, [projectId, setProjectId, setSpaceId, setProjectName]);

  useEffect(() => {
    const checkSupport = async () => {
      const isSupported = await Compositor.isSupported();
      setIsWebCodecsSupported(isSupported);
    };
    checkSupport();
  }, []);

  return (
    <div className="h-screen w-screen flex flex-col bg-background overflow-hidden">
      {!isReady && (
        <div className="absolute inset-0 z-100">
          <Loading />
        </div>
      )}
      <Header />
      <div className="flex-1 min-h-0 min-w-0">
        <ResizablePanelGroup direction="horizontal" className="h-full w-full gap-0">
          {/* Left Column: Media Panel */}
          <ResizablePanel
            defaultSize={toolsPanel}
            minSize={15}
            maxSize={40}
            onResize={setToolsPanel}
            className="max-w-7xl relative overflow-visible! bg-card min-w-0"
          >
            <MediaPanel />
            <FloatingControl />
          </ResizablePanel>

          <ResizableHandle className="bg-border/90" />

          {/* Middle Column: Preview + Timeline */}
          <ResizablePanel
            defaultSize={isCopilotVisible ? 100 - copilotPanel - toolsPanel : 100 - toolsPanel}
            minSize={40}
            className="min-w-0 min-h-0"
          >
            <ResizablePanelGroup direction="vertical" className="h-full w-full gap-0">
              {/* Canvas Panel */}
              <ResizablePanel
                defaultSize={mainContent}
                minSize={30}
                maxSize={85}
                onResize={setMainContent}
                className="min-h-0"
              >
                <CanvasPanel
                  onReady={() => {
                    setIsReady(true);
                  }}
                />
              </ResizablePanel>

              <ResizableHandle className="bg-border/90" />

              {/* Timeline Panel */}
              <ResizablePanel
                defaultSize={timeline}
                minSize={15}
                maxSize={70}
                onResize={setTimeline}
                className="min-h-0"
              >
                <Timeline />
              </ResizablePanel>
            </ResizablePanelGroup>
          </ResizablePanel>
          {isCopilotVisible && (
            <>
              <ResizableHandle className="bg-border/90" />
              {/* Right Column: Chat Copilot */}
              <ResizablePanel
                defaultSize={copilotPanel}
                minSize={15}
                maxSize={40}
                onResize={setCopilotPanel}
                className="max-w-4xl min-w-[360px] relative overflow-visible! bg-card min-w-0"
              >
                {/* Chat copilot */}
                <Assistant />
              </ResizablePanel>
            </>
          )}
        </ResizablePanelGroup>
      </div>

      {/* WebCodecs Support Check Modal */}
      <WebCodecsUnsupportedModal open={!isWebCodecsSupported} />

      {/* AI Generator Modal */}
      <AssetGeneratorModal />
    </div>
  );
}
